#!/usr/bin/ruby

#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
#Let us list the factors of the first seven triangle numbers:
#
#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28
#
#We can see that 28 is the first triangle number to have over five divisors.
#
#What is the value of the first triangle number to have over five hundred divisors?

# yeah, let's use prime_division again...
# but, wait... I think I was going into a trap if I use prime_division directly... yeah, it's a little slow. it works, but it needs around 1m13s.
# so, I have to choose another way.
require 'mathn'

n = 1
m = 1
sum = 0
while n <= 500 do
  sum += m
  k = sum.prime_division
  n = 1
  k.each do |p|
    n = n * ( p[1] + 1 )
  end
  m += 1
end
p sum
