#!/usr/bin/ruby

# How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

a=(2..100).to_a
b=[]
a.each do |p|
  a.each do |c|
    b << p**c
  end
end
p b.uniq.length
