#!/usr/bin/ruby

#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.

def tri(n)
  n*(n+1)/2
end

def is_pent?(n)
  return true if (1+Math.sqrt(1+24*n))/6 % 1 == 0
  return false
end

def is_hex?(n)
  return true if (1+Math.sqrt(1+8*n))/4 % 1 == 0
end

(2..100000).each do |m|
  next if m == 285
  a = tri(m)
  if is_pent?(a) && is_hex?(a)
    p m
    p a
    exit
  end
end
  
